my_app/admin/controllers.py
#!/usr/bin/python

import collections
import json

from flask import render_template, g, request, Blueprint, redirect, url_for
from flask_login import login_required, current_user, login_user, flash, logout_user, session
from flask_wtf import Form
from wtforms import SelectField, StringField, SelectMultipleField
from wtforms.validators import InputRequired

from my_app import lm, bcrypt, db, app
from my_app.auth.forms import LoginForm
from my_app.auth.models import Users, TicketTemplate
from utils import dynaform
from utils.ldap_form import SimpleForm
from utils.process_form_request import process_all

# Define the blueprint: 'admin'
admin = Blueprint('admin', __name__, template_folder='templates', static_folder='static')


# Set the route and accepted methods
@admin.before_request
def before_request():
    if current_user.is_authenticated:
        g.user = current_user  # return username in get_id()
    else:
        g.user = None  # or 'some fake value', whatever


@lm.user_loader
def load_user(id):
    return Users.query.get(int(id))


@admin.route('/admin', methods=['GET', 'POST'])
@admin.route('/admin/', methods=['GET', 'POST'])
def admin_login():
    print app.config
    # If sign in form is submitted
    if g.user is None or not g.user.is_admin():
        form = LoginForm()
        if form.validate_on_submit():
            user = Users.query.filter_by(username=form.login_name.data).first()
            if user and user.is_admin() and bcrypt.check_password_hash(user.passwd, form.password_field.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(url_for('admin.admin_index'))
            flash("Username or Password is invalid", 'error')
        return render_template('admin_login.html', form=form)
    else:
        return redirect(url_for('admin.admin_index'))


@admin.route('/admin/index')
@login_required
def admin_index():
    return render_template('admin_index.html')


@admin.route('/admin/AD', methods=['GET', 'POST'])
@login_required
def ad_module():
    form = SimpleForm()
    if form.validate_on_submit():
        attr_list = form.attr_form.data
        app.config.update(AD_ATTR=attr_list)
        return redirect(url_for('.admin_index'))
    else:
        flash('choose at least one attribute', 'error')
        # print form.errors
    return render_template('admin_AD_module.html', form=form)


@admin.route('/admin/logout', methods=['GET'])
@login_required
def admin_logout():
    logout_user()
    return render_template('admin_logout.html')


@admin.route('/admin/template/<step>', methods=['GET', 'POST'])
@login_required
def template_wizard(step):

    if step == 'choose':

        template_types = TicketTemplate.query.all()
        templates_present = [i.issuetype for i in template_types]

        class PickIssueType(Form):
            issue_type = SelectField('IssueType', [InputRequired()],
                                     choices=[(element, element) for element in
                                              app.config['JIRA_ISSUE_TYPES'] if
                                              element not in templates_present])

        session['type'] = ''
        form = PickIssueType()
        if form.validate_on_submit():
            session['type'] = request.form['issue_type']
            return redirect(url_for('.template_wizard', step='process'))
        return render_template('admin_template.html', form=form, step='choose')

    if step == 'process':

        def get_dicts_admin(type_of_issue):
            with open(app.config['JIRA_SOURCE_FILES'][type_of_issue], 'r') as data_file:
                fields = json.load(data_file)
            json_form = fields
            return dynaform.get_form(json_form)

        jira_dict_admin = get_dicts_admin(session['type'])

        # class definitions
        class BaseFormAdmin(Form):
            def __iter__(self):
                ordered_fields = collections.OrderedDict()
                for element in getattr(self, 'field_order', []):
                    ordered_fields[element] = self._fields.pop(element)
                ordered_fields.update(self._fields)
                self._fields = ordered_fields
                return super(BaseFormAdmin, self).__iter__()

        class NewFormAdmin(BaseFormAdmin):
            pass

        # NewFormAdmin.resolved = BooleanField('Resolve issue')
        # NewFormAdmin.comment = StringField('Comment')
        for name in jira_dict_admin:
            setattr(NewFormAdmin, name, jira_dict_admin.get(name))

        class FormDefault(NewFormAdmin):
            project = StringField('Project', default='ITS')
            issuetype = StringField('Issuetype', default=session['type'])
            summary = StringField('Summary')
            labels = SelectMultipleField('Labels', choices=[(c[0], c[1]) for c in jira_dict_admin.get(
                'labels').kwargs['choices']], render_kw={'size': 3})
            customfield_10802 = SelectField('Reporting department',
                                            choices=[(c[0], c[1]) for c in jira_dict_admin.get(
                                                'customfield_10802').kwargs['choices']])
            customfield_11603 = SelectField('Categories-SR', choices=[(c[0], c[1]) for c in jira_dict_admin.get(
                'customfield_11603').kwargs['choices']])

            customfield_11603_child = SelectField('Categories-SR-child',
                                                  choices=[(c[0], c[1]) for c in jira_dict_admin.get(
                                                      'customfield_11603_child').kwargs['choices']])
            assignee = StringField('Assignee')
            reporter = StringField('Reporter')
            customfield_11600 = StringField('Requester')
            description = StringField('Description')
            field_order = ('project', 'summary', 'issuetype', 'labels', 'customfield_10802', 'assignee', 'reporter',
                           'customfield_11600', 'customfield_11603', 'customfield_11603_child', 'description')

        form = FormDefault()
        step = 'process'
        formdata = None
        if request.method == 'POST':
            if form.validate_on_submit():
                flash('processing and saving your form to database', 'message')
                process_all(request.form, g.user, session['type'])
                return redirect(url_for('admin.template_wizard', step='list'))
            else:
                flash('there were errors processing your request', 'error')
        return render_template('admin_template.html', **locals())

    if step == 'list':
        template_list = TicketTemplate.query.filter(TicketTemplate.title.like("default_%")).all()
        return render_template('admin_template.html', step='list', all=template_list)


@admin.route('/admin/synchro/', methods=['GET', 'POST'])
@login_required
def synchronize():
    pass

my_app/admin/templates/admin_AD_module.html
{% extends 'admin_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    {{ wtf.quick_form(form) }}
{%  endblock %}

my_app/admin/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JIRA HotDesk Admin</title>
</head>
<body>
    Admin
        {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
    {% for message in messages %}
        <li>{{ message }} </li>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
<p><a href="{{ url_for('admin.admin_logout') }}">Log out</a></p>
</body>
</html>

my_app/admin/templates/admin_forms.html
{% macro render(field) %}
    {% set current_step = kwargs.get('step', None) %}
    {% set form_admin = kwargs.get('form', None) %}

    {% if current_step=='list' %}
        {% set list_of_templates = kwargs.get('all_list', None) %}
        {% if not list_of_templates %}
            <p>No templates found, <a href="{{ url_for('admin.template_wizard', step='choose') }}">create</a> some</p>
        {% else %}
        <table>
        <thead>
            <tr>
                <th>Issuetype</th><th>Title</th><th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for item in list_of_templates %}
                <tr><td>{{ item.issuetype}}</td><td>{{ item.title }}</td><td>{{ item.description }}</td></tr>
            {% endfor %}
        </tbody>
        </table>
            <p><a href="{{ url_for('admin.template_wizard', step='choose') }}">Create</a> new</p>
        {% endif %}
    {% endif %}


    {% if current_step=='process' %}
        <form action="" method="post" name="create_template">
        <fieldset>
        <div class="form-group">
        {#<div>
            <p>{{ form.labels.label }} {{ form.labels}}
            <p>{{ form.labels.label }} {{ form.labels}}
                <input type="checkbox" id="{{form.labels.name}}" name = "save" value={{form.labels.name}}>Save
                <input type="checkbox" id="{{form.labels.name}}" name = "required" value={{form.labels.name}}>Required
            </p>
            <p>{{ form.customfield_10802.label }}{{ form.customfield_10802 }}
                <input type="checkbox" id="{{form.customfield_10802.name}}" name = "save" value={{form.customfield_10802.name}}>Save
                <input type="checkbox" id="{{form.customfield_10802.name}}" name = "required" value={{form.customfield_10802.name}}>Required
            </p>
        </div>#}

{# list here all standard fields with classes and visuals
and in loop rest #}

{% for field in form_admin if field.name != "customfield_11603_child" %}
{% if field.type in ['CSRFTokenField', 'HiddenField'] %}
  {{ field() }}
{% else %}

    <p>{% if field.flags.required %}*{% endif %} {{ field.label }}
      {% if field.name != "resolved" %}
        {{ field() }}
        {% endif %}
        {% if field.name == "customfield_11603" %}

        <span>{{ form_admin.customfield_11603_child }}</span>
        {% endif %}
        <label for="{{field.name}}">Save</label><input type="checkbox" id="{{field.name}}" name = "save" value={{field.name}}>
        <label for="{{field.name}}">Required</label><input type="checkbox" id="{{field.name}}" name = "required" value={{field.name}}>
{% endif %}
      {% if field.errors or field.help_text %}
        <span class="help-inline">
        {% if field.errors %}
          {{ field.errors|join(' ') }}
        {% else %}
          {{ field.help_text }}
        {% endif %}
        </span>
      {% endif %}
    </p>
  </div>
{% endfor %}
	<button type="submit">Save Template</button>
</fieldset>
</form>

    {% elif current_step =='choose' %}
    <div>

    <form action="" method="post" name="choose_issuetype">
    {{ form_admin.csrf_token }}
    <fieldset>
        {{ form_admin.issue_type.label }} {{ form_admin.issue_type }}
        <p>
            <span class="help-inline">
                {% if form_admin.issue_type.errors %}
                    {{ form_admin.issue_type.errors|join(' ') }}
                {% else %}
                    {{ form_admin.issue_type.help_text }}
                {% endif %}
                </span>
        </p>
        <p><input type="submit" value="Choose">
        </p>
    </fieldset>
    </form>
    </div>
    {% endif %}
{% endmacro %}

my_app/admin/templates/admin_index.html
{% extends 'admin_base.html' %}

{% block content %}

    <h3>Configure JIRA default templates</h3>
    <a href="{{ url_for('admin.template_wizard', step='list') }}">Configure</a>

    <h3>Configure AD fields</h3>
    <a href="{{ url_for('admin.ad_module') }}">Configure</a>

{% endblock %}

my_app/admin/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Sign In</h1>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
    {% for message in messages %}
        <li>{{ message }} </li>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}

    <form action="" method="post" name="login">
        {{ form.hidden_tag() }}
        <p>
            {{ form.login_name(size=25) }}
                 <span class="help-inline">
                {% if form.login_name.errors %}
                    {{ form.login_name.errors|join(' ') }}
                {% else %}
                    {{ form.login_name.help_text }}
                {% endif %}
                </span><br>
            <br>
            {{ form.password_field(size=30) }}
                <span class="help-inline">
                {% if form.password_field.errors %}
                    {{ form.password_field.errors|join(' ') }}
                {% else %}
                    {{ form.password_field.help_text }}
                {% endif %}
                </span><br>
        </p>

        <p><input type="submit" value="Log In"></p>
    </form>
    <h3> Or go back to <a href="{{ url_for('index') }}">main</a> page
</body>
</html>

my_app/admin/templates/admin_logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        <h3>Logged out</h3>
    </div>
    <div>
        <p><a href="{{ url_for('admin.admin_login') }}">Log in again</a></p>
</body>
</html>

my_app/admin/templates/admin_template.html
{% extends "admin_base.html" %}
{% from "admin_forms.html" import render %}
{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
    {{ render(form = form, step=step, all_list=all) }}
{% endblock %}