my_app/profile/controllers.py
#!/usr/bin/python

import json, urllib2

from ldap3 import SUBTREE

from jira import JIRAError

from flask import (
    render_template, g, request, Blueprint, redirect, url_for,
    flash, session, jsonify
)
from flask.ext.login import login_required, current_user
from flask_wtf import Form
from wtforms import StringField, SelectField, BooleanField
from wtforms.validators import InputRequired

from my_app import app, jira_conn, lm, ldap_ac, db
from my_app.auth.models import TicketTemplate, Users
from utils import dynaform
from utils.process_form_request import process_all
from utils.create_ticket import create_ticket_jira

# Define the blueprint: 'profile'
profile = Blueprint('profile', __name__, template_folder='templates',
                    static_folder='static', static_url_path=app.config['BASE_DIR'] + '/my_app/profile')

#######################################################
# helper function, return jira status can be ['ONLINE', 'OFFLINE', 'SYNCHRO']
# SYNCHRO - rebuilding templates - access suspended


def get_jira_status():
    jira_stat = db.engine.execute("SELECT status FROM JIRA_STATUS").fetchone()
    return jira_stat[0]


@lm.user_loader
# Given *user_id*, return the associated User object.
def load_user(id):
    return Users.query.get(int(id))


# Set the route and accepted methods
@profile.before_request
def before_request():
    if current_user.is_authenticated:
        g.user = current_user  # return username in get_id()
    else:
        g.user = None  # or 'some fake value', whatever

    g.status = get_jira_status()


@profile.route('/my_templates')
@login_required
def templates_list():
    if not request.script_root:
        request.script_root = url_for('index', _external=True)
    u_id = g.user.get_id()
    templates_list_user = TicketTemplate.query.filter_by(user_id=u_id).all()
    if len(templates_list_user) == 0:
        return render_template('profile.html', attr=app.config['AD_ATTR'])
    else:
        return render_template('profile.html', templates_user=templates_list_user,
                               attr=app.config['AD_ATTR'])


# route tickets archive
@profile.route('/created_tickets')
@login_required
def tickets_archive():
    if jira_conn.connection():
        print "ok"
        # print jira_conn.connection().search_issues('assignee = {0}'.format(g.user.username))
    else:
        print 'some problem'
    return render_template('archive.html', step='archive')


@profile.route('/my_templates/<template_id>', methods=['GET', 'POST'])
@login_required
def open_template(template_id):
    # open template to create ticket
    chosen_template = TicketTemplate.query.filter_by(guid=template_id).first()
    chosen_template_json = json.loads(chosen_template.json_form)
    chosen_template_dict = dynaform.get_form(chosen_template_json)

    sr_categories = None
    try:
        sr_categories = json.load(file(app.config['BASE_DIR'] + '/utils/customfield_11603.json', 'r'))
    except Exception as e:
        print e.message

    if sr_categories is None:
        pass

    class TemplateForm(Form):
        pass

    for template_form in chosen_template_dict:
        setattr(TemplateForm, template_form, chosen_template_dict.get(template_form))

    form = TemplateForm(request.form)
    form_issuetype = chosen_template.issuetype
    form_title = chosen_template.title
    form_project = chosen_template.project
    attr = app.config['AD_ATTR']
    sr_all = json.dumps(sr_categories)

    if request.method == 'GET':
        if g.status == 'ONLINE':
            return render_template('open_template.html', **locals())
        if g.status == 'OFFLINE':
            flash("JIRA is Offline", "info")
            return render_template('open_template.html', **locals())
        if g.status == 'SYNCHRO':
            print 'synchro'

    if request.method == 'POST':
        print g.status
        import httplib2
        h = httplib2.Http()
        resp = h.request(app.config['JIRA_SERVER'], 'HEAD')
        assert int(resp[0]['status']) < 400

        if form.validate_on_submit():
            response = create_ticket_jira(request.form, issuetype=form_issuetype, project=form_project)
            if isinstance(response, JIRAError):
                # we got an error
                print "text " + response
                flash(response.text, 'error')
            else:
                # dict_ = ast.liter al_eval(text.response.text)
                return redirect(url_for('profile.templates_list'))
        else:
            flash('there were errors processing your request', 'error')
    # return render_template('open_template.html', **locals())


@profile.route('/my_templates/edit/<template_id>', methods=['GET', 'POST'])
@login_required
def edit_template(template_id):
    chosen_template = TicketTemplate.query.filter_by(guid=template_id).first()
    chosen_template_json = json.loads(chosen_template.json_form)

    for element in chosen_template_json:
        if element['required'] is True:
            if element.get('default', None) is None:
                element.update({'default': ' '})

    sr_categories = None
    try:
        sr_categories = json.load(file(app.config['BASE_DIR'] + '/utils/customfield_11603.json', 'r'))
    except Exception as e:
        print e

    if sr_categories is None:
        pass

    chosen_template_dict = dynaform.get_form(chosen_template_json)

    form_title = chosen_template.title
    form_description = chosen_template.description

    class TemplateForm(Form):
        pass

    TemplateForm.title = StringField('Name of template', [InputRequired()], default=form_title)
    TemplateForm.description_template = StringField('Short Description of template', [InputRequired()],
                                                    default=form_description)
    for template_form in chosen_template_dict:
        setattr(TemplateForm, template_form, chosen_template_dict.get(template_form))

    form = TemplateForm(request.form)
    form_issuetype = chosen_template.issuetype
    form_project = chosen_template.project
    sr_all = json.dumps(sr_categories)

    if request.method == 'POST':
        if form.validate_on_submit():
            print request.form
            process_all(request.form, g.user, form_issuetype, template_id=template_id)
            return redirect(url_for('profile.open_template', template_id=template_id))
        else:
            flash('there were errors processing your request', 'error')
    return render_template('edit_template.html', **locals())


@profile.route('/create_template/<step>', methods=['GET', 'POST'])
@login_required
def create_template(step):
    if not request.script_root:
        request.script_root = url_for('index', _external=True)

    class PickIssueType(Form):
        issue_type_select = SelectField('IssueType', [InputRequired()],
                                        choices=[(element, element) for element in
                                                 app.config['JIRA_ISSUE_TYPES']])

    sr_categories = None
    try:
        sr_categories = json.load(file(app.config['BASE_DIR'] + '/utils/customfield_11603.json', 'r'))
    except Exception as e:
        print e.message

    if sr_categories is None:
        pass

    if step == 'choose':

        user = Users.query.filter_by(id=g.user.get_id()).first()

        session['type'] = ''
        form = PickIssueType()
        if form.validate_on_submit():
            session['type'] = request.form['issue_type_select']
            return redirect(url_for('.create_template', step='process'))
        return render_template('user_template.html', form=form, step='choose', sr_all=sr_categories)

    if step == 'process':

        # get from database default json
        default_template = TicketTemplate.query.filter(
            TicketTemplate.title.like("default_" + session['type'])).first()

        # source json for dynaform class
        fields = json.loads(default_template.json_form)
        jira_dict_user = dynaform.get_form(fields)
        project = ''
        issuetype = default_template.issuetype

        for field in fields:
            if field['name'] == 'project':
                project = field['default']

        class UserTemplate(Form):
            pass

        UserTemplate.resolved = BooleanField('Resolve issue', default=False)
        # needed regexp to check if string is in format (3w 2d 12h 5m)
        # UserTemplate.time_spent = StringField('Time spent', [Regexp(), InputRequired()])
        UserTemplate.time_spent = StringField('Time spent', [InputRequired()], default=' ')
        UserTemplate.comment = StringField('Comment')
        UserTemplate.title = StringField('Name of template', [InputRequired()])
        UserTemplate.description_template = StringField('Short Description of template', [InputRequired()])
        for name in jira_dict_user:
            setattr(UserTemplate, name, jira_dict_user.get(name))

        form = UserTemplate(request.form)
        formdata = None
        sr_all = sr_categories
        step = 'process'
        project = project
        issuetype = issuetype

        if request.method == 'POST':
            if form.validate_on_submit():
                process_all(request.form, g.user, session['type'])
                return redirect(url_for('profile.templates_list'))
            else:
                flash('there were errors processing your request', 'error')
        return render_template("user_template.html", **locals())


@profile.route('/_search_user', methods=['POST'])
def search_ldap_user():
    response = request.get_json()
    user = response['username']
    search_base = app.config['LDAP_GLOBAL_FILTER']

    search_filter = '(&' + search_base + '(|(sn={0})(sn={0}*)(cn={0}*)(cn=*{0})(givenName={0})))'.format(user)
    connection = ldap_ac.connection
    results = connection.extend.standard.paged_search(search_base=app.config['LDAP_BASE_DN'],
                                                      search_filter=search_filter,

my_app/profile/templates/archive.html
{%- extends "base.html" %}

{% block navbar %}

{% include 'navbar.html' %}

{% endblock %}

my_app/profile/templates/base_create_ticket.html
{%- extends "bootstrap/base.html" %}
{% import "bootstrap/fixes.html" as fixes %}
{% import "bootstrap/utils.html" as utils %}

{% block title %}JIRA Hotdesk{% endblock %}


{% block head %}
{{super()}}
    {{fixes.ie8()}}
{% endblock %}

{% block styles %}
{{super()}}
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='base_style.css') }}">
{% endblock %}

<body {% block body_attribs %} data-root="{{ url_for('.search_ldap_user') }}" {% endblock body_attribs %}  >
{% block body  %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src={{ url_for('profile.static', filename = 'ldap_form.js') }} ></script>
    <script type="text/javascript" src={{ url_for('profile.static', filename='drop_down.js') }} ></script>
    <script type="text/javascript" src={{ url_for('profile.static', filename='validate.js') }} ></script>
    <script type="text/javascript"> set_sr_cat({{ sr_all|safe|tojson }}) </script>
{% endblock %}
    {% block content %}
        {% endblock %}
{% endblock body %}
</body>

my_app/profile/templates/base_new_edit.html
{%- extends "bootstrap/base.html" %}
{% import "bootstrap/fixes.html" as fixes %}

{% block title %}JIRA Hotdesk{% endblock %}


{% block head %}
{{super()}}
    {{fixes.ie8()}}
{% endblock %}

{% block styles %}
{{super()}}
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='base_style.css') }}">
{% endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block scripts %}
    {{ super() }}

    <script type="text/javascript" src={{ url_for('profile.static', filename='drop_down.js') }} ></script>
    <script type="text/javascript"> set_sr_cat({{ sr_all|safe|tojson }}) </script>

{% endblock %}

my_app/profile/templates/base_profile.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/fixes.html" as fixes %}

{% block title %}JIRA Hotdesk{% endblock %}


{% block head %}
{{super()}}
    {{fixes.ie8()}}
{% endblock %}

{% block styles %}
{{super()}}
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='base_style.css') }}">
{% endblock %}

<body {% block body_attribs %} data-root="{{ url_for('.search_ldap_user') }}" {% endblock body_attribs %}  >
{% block body  %}


{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src={{ url_for('profile.static', filename = 'ldap_form.js') }} ></script>
{#    <script type="text/javascript" src={{ url_for('profile.static', filename='drop_down.js') }} async></script>#}
{#  <script type="text/javascript" src={{ url_for('static', filename='validate.js') }} async></script>#}
{% endblock %}
    {% block content %}
        {% endblock %}
{% endblock body %}
  </body>

my_app/profile/templates/edit_template.html
{% extends 'base_new_edit.html' %}
{% import "bootstrap/utils.html" as utils %}

{% block content %}

    <p>{{ form_project }} {{ form_issuetype }}</p>
        <p>{{ form_title }}</p>

        <form action="" method="post" name="edit_template">
            <fieldset><div class="form-group">
                {% for field in form if field.name != "customfield_11603_child" %}
                    {% if field.type in ['CSRFTokenField', 'HiddenField'] %} {{ field() }}
                    {% else %}
                        <p>{% if field.flags.required %}*{% endif %}
                        {% if field.name in ('title', 'description_template') %} {{ field.label }} {{ field() }}
                        {% else %}
                            {{ field.label }} {{ field() }}
                            {% if field.name == "customfield_11603"%}
                                <span>{{ form['customfield_11603_child'] }}</span>
                            {% endif %}
                        {% endif %}
                        {% if field.errors or field.help_text %}
                        <span class="help-inline">
                            {% if field.errors %}
                                {{ field.errors|join(' ') }}
                            {% else %}
                                {{ field.help_text }}
                            {% endif %}
                        </span>
                        {% endif %}
                        </p>
                    {% endif %}
                {% endfor %}

            </div>
        <button type="submit">Save template</button>
    </fieldset>
    </form>

{% endblock %}

my_app/profile/templates/forms.html
{% macro render(field) %}
    {% set current_step = kwargs.get('step', None) %}
    {% set form = kwargs.get('form', None) %}


    {% if current_step =='choose' %}

        <div class="jumbotron">
            <div class="container-fluid">
                <div>
                    <form action="" method="post" name="choose_issuetype">
                        {{ form.csrf_token }}
                        <fieldset>

                        <p>
                            {{ form.issue_type_select.label }} {{ form.issue_type_select }}
                            <span class="help-inline">
                            {% if form.issue_type_select.errors %}
                                {{ form.issue_type_select.errors|join(' ') }}
                            {% else %}
                                {{ form.issue_type_select.help_text }}
                            {% endif %}
                            </span>
                        </p>
                        <p>
                            <input type="submit" value="Choose">
                        </p>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>


    {% elif current_step=='process' %}
        {% set sr_all = kwargs.get('sr_all', None) %}
        {% set project = kwargs.get('project', None) %}
        {% set issuetype = kwargs.get('issuetype', None) %}

        <p>{{ project }} {{ issuetype }}</p>
        <form id="create_template" action="" method="post" name="create_template">
            <fieldset><div class="form-group">
{#            {{ form.time_spent }}#}
                {% for field in form if field.name != "customfield_11603_child" %}
                    {% if field.type in ['CSRFTokenField', 'HiddenField'] %} {{ field() }}
                    {% else %}
                        <p>{% if field.flags.required %}*{% endif %}
                        {% if field.name in ('title', 'description_template') %} {{ field.label }} {{ field() }}
                        {% else %}
                            {{ field.label }} {{ field() }}
                            {% if field.name == "customfield_11603"%}
                                <span>{{ form['customfield_11603_child'] }}</span>
                            {% endif %}
                        {% endif %}

                    {% if field.errors or field.help_text %}
                        <span class="help-inline">
                    {% if field.errors %}
                        {{ field.errors|join(' ') }}
                    {% else %}
                        {{ field.help_text }}
                    {% endif %}
                </span>
              {% endif %}
            </p>
          </div>
        {% endif %}
        {% endfor %}
        <button type="submit">Save</button>
    </fieldset>
    </form>
    {% endif %}
{% endmacro %}

my_app/profile/templates/ldap_search.html
{% block content %}
    <h2> Search user: </h2>

    <div>
        <input type="text" id="user_search" placeholder="Search user...">
        <a id="ldap_search" href="#">&#128269;</a>
    </div>

    <p id="result"> </p>

    <div class="dropdown">

        <button class="btn btn-default dropdown-toggle" type="button" id="search_ad_results" data-toggle="dropdown">
            Results
        <span class="caret"></span></button>
        <span class="ldap_search_info hidden" id="ldap_search_info"></span>
        <ul class="dropdown-menu hidden" id="ldap_results">

        </ul>
    </div>
        <div id="ldap_user_info">
        {% for element in attr %}
            <div class="row">
                <div class="col-md-3">
                    <label>{{ attr[element] }}</label>
                </div>
                <div class="col-md-4">
                    <input id={{ element }} class="text-left">
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock %}

my_app/profile/templates/open_template.html
{% extends 'base_create_ticket.html' %}
{% import "bootstrap/utils.html" as utils %}

{% block content %}



  {%- with messages = get_flashed_messages(with_categories=True) %}
  {%- if messages %}

        {{utils.flashed_messages(messages, dismissible=True)}}
  {%- endif %}
  {%- endwith %}

    <div class="modal-body row">
        <div class="col-md-7">
            <div class="jumbotron">
                <div class="container-fluid">

<p>{{ form_project }} {{ form_issuetype }}</p>
        <p>{{ form_title }}</p>
        <form action="" method="post">
            <fieldset><div class="form-group">
                {% for field in form if field.name != "customfield_11603_child" %}
                    {% if field.type in ['CSRFTokenField', 'HiddenField'] %} {{ field() }}
                    {% else %}
                        <p>{% if field.flags.required %}*{% endif %}

                            {{ field.label }} {{ field() }}
                            {% if field.name == "customfield_11603"%}
                                <span>{{ form['customfield_11603_child'] }}</span>
                            {% endif %}

                        {% if field.errors or field.help_text %}
                        <span class="help-inline">
                            {% if field.errors %}
                                {{ field.errors|join(' ') }}
                            {% else %}
                                {{ field.help_text }}
                            {% endif %}
                        </span>
                        {% endif %}
                        </p>
                    {% endif %}
                {% endfor %}

            </div>
        <button type="submit">Create ticket</button>
    </fieldset>
    </form>
                    </div>
            </div>
        </div>

           <div class="col-md-5">
            <div class="jumbotron">
                <div class="container-fluid">
                    {% include "ldap_search.html" %}
                </div>
            </div>
        </div>

{% endblock %}

my_app/profile/templates/profile.html
{% extends "base_profile.html" %}
{% import "bootstrap/utils.html" as utils %}


{% block content %}
    <div class="modal-body row">
        <div class="col-md-7">
            <div class="jumbotron">
                <div class="container-fluid">
                    {#% set list_of_templates = kwargs.get('templates_user', None) %#}
                    <h2> Your templates: </h2>
                    <ul class="list-group">
                        {% for item in templates_user %}
                            <li class="list-group-item clearfix" style="display: flex; align-items: center">
                                <div class="col-md-7" style="word-wrap: break-word; display: inline-block">
                                    <h4 class="list-group-item-heading">{{ item.title }}</h4>
                                    <p class="list-group-item-text"> {{ item.description }}
                                        {% if item.issuetype == 'Incident' %}
                                            <span class="label label-danger">{{ item.issuetype }}</span>
                                        {% elif item.issuetype == 'Service Request' %}
                                            <span class="label label-primary">{{ item.issuetype }}</span>
                                        {% elif item.issuetype == 'SR-Permission' %}
                                            <span class="label label-success">{{ item.issuetype }}</span>
                                        {% elif item.issuetype == 'Task' %}
                                            <span class="label label-default">{{ item.issuetype }}</span>
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="col-md-5">
                                    <span class="pull-right button-group">
                                        <a href="{{ url_for('profile.edit_template', template_id=item.guid) }}"
                                           class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>
                                    Edit</a>
                                    <a href="{{ url_for('profile.open_template', template_id=item.guid) }}"
                                       class="btn btn-primary"><span class="glyphicon glyphicon-open"></span> Open</a>
                                    </span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    {% if not templates_user %}
                        <p>No templates found, create some</p>
                    {% else %}

                    {% endif %}

                    <p><a href="{{ url_for('.create_template', step='choose') }}">Create</a> new template
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="jumbotron">
                <div class="container-fluid">
                    {% include "ldap_search.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

my_app/profile/templates/user_template.html
{% extends 'base.html' %}
{% from "forms.html" import render %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}
{{ render(form = form, step=step, sr_categories = sr_categories,
    sr_all = sr_all, project = project, issuetype = issuetype ) }}

{% endblock %}



{% block footer %}

{% endblock %}